const data = [
  {
    class: 6,
    group: "",
    section: "A",
    category: "total",
    boys: "30",
    girls: "10",
  },
  {
    class: 6,
    group: "",
    section: "A",
    category: "muslim",
    boys: "22",
    girls: "44",
  },
  {
    class: 6,
    group: "",
    section: "A",
    category: "hindu",
    boys: "1",
    girls: "2",
  },
  {
    class: 6,
    group: "",
    section: "A",
    category: "stipend",
    boys: "66",
    girls: "66",
  },
  {
    class: 6,
    group: "",
    section: "A",
    category: "merit_stipend",
    boys: "66",
    girls: "66",
  },
  {
    class: 6,
    group: "",
    section: "A",
    category: "repeater",
    boys: "66",
    girls: "66",
  },
  {
    class: 6,
    group: "",
    section: "A",
    category: "transfer_in",
    boys: "66",
    girls: "66",
  },
  {
    class: 6,
    group: "",
    section: "A",
    category: "transfer_out",
    boys: "66",
    girls: "66",
  },
  {
    class: 6,
    group: "",
    section: "A",
    category: "final_attendence",
    boys: "66",
    girls: "66",
  },
  {
    class: 6,
    group: "",
    section: "A",
    category: "final_promotion",
    boys: "66",
    girls: "66",
  },
  {
    class: 6,
    group: "",
    section: "B",
    category: "total",
    boys: "২৫",
    girls: "২১",
  },
  {
    class: 6,
    group: "",
    section: "B",
    category: "muslim",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "B",
    category: "hindu",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "B",
    category: "stipend",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "B",
    category: "merit_stipend",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "B",
    category: "repeater",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "B",
    category: "transfer_in",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "B",
    category: "transfer_out",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "B",
    category: "final_attendence",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "B",
    category: "final_promotion",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "C",
    category: "total",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "C",
    category: "muslim",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "C",
    category: "hindu",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "C",
    category: "stipend",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "C",
    category: "merit_stipend",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "C",
    category: "repeater",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "C",
    category: "transfer_in",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "C",
    category: "transfer_out",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "C",
    category: "final_attendence",
    boys: "6",
    girls: "6",
  },
  {
    class: 6,
    group: "",
    section: "C",
    category: "final_promotion",
    boys: "6",
    girls: "6",
  },
  {
    class: 7,
    group: "",
    section: "A",
    category: "total",
    boys: "70",
    girls: "27",
  },
  {
    class: 7,
    group: "",
    section: "A",
    category: "muslim",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "A",
    category: "hindu",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "A",
    category: "stipend",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "A",
    category: "merit_stipend",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "A",
    category: "repeater",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "A",
    category: "transfer_in",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "A",
    category: "transfer_out",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "A",
    category: "final_attendence",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "A",
    category: "final_promotion",
    boys: "11",
    girls: "5",
  },
  {
    class: 7,
    group: "",
    section: "B",
    category: "total",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "B",
    category: "muslim",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "B",
    category: "hindu",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "B",
    category: "stipend",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "B",
    category: "merit_stipend",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "B",
    category: "repeater",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "B",
    category: "transfer_in",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "B",
    category: "transfer_out",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "B",
    category: "final_attendence",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "B",
    category: "final_promotion",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "C",
    category: "total",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "C",
    category: "muslim",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "C",
    category: "hindu",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "C",
    category: "stipend",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "C",
    category: "merit_stipend",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "C",
    category: "repeater",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "C",
    category: "transfer_in",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "C",
    category: "transfer_out",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "C",
    category: "final_attendence",
    boys: "7",
    girls: "7",
  },
  {
    class: 7,
    group: "",
    section: "C",
    category: "final_promotion",
    boys: "7",
    girls: "7",
  },
  {
    class: 8,
    group: "",
    section: "A",
    category: "total",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "A",
    category: "muslim",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "A",
    category: "hindu",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "A",
    category: "stipend",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "A",
    category: "merit_stipend",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "A",
    category: "repeater",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "A",
    category: "transfer_in",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "A",
    category: "transfer_out",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "A",
    category: "final_attendence",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "A",
    category: "final_promotion",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "B",
    category: "total",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "B",
    category: "muslim",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "B",
    category: "hindu",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "B",
    category: "stipend",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "B",
    category: "merit_stipend",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "B",
    category: "repeater",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "B",
    category: "transfer_in",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "B",
    category: "transfer_out",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "B",
    category: "final_attendence",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "B",
    category: "final_promotion",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "C",
    category: "total",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "C",
    category: "muslim",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "C",
    category: "hindu",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "C",
    category: "stipend",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "C",
    category: "merit_stipend",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "C",
    category: "repeater",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "C",
    category: "transfer_in",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "C",
    category: "transfer_out",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "C",
    category: "final_attendence",
    boys: "8",
    girls: "8",
  },
  {
    class: 8,
    group: "",
    section: "C",
    category: "final_promotion",
    boys: "8",
    girls: "8",
  },
  {
    class: 9,
    group: "science",
    section: "A",
    category: "total",
    boys: "90",
    girls: "89",
  },
  {
    class: 9,
    group: "science",
    section: "A",
    category: "muslim",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "A",
    category: "hindu",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "A",
    category: "stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "A",
    category: "merit_stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "A",
    category: "repeater",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "A",
    category: "transfer_in",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "A",
    category: "transfer_out",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "A",
    category: "final_attendence",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "A",
    category: "final_promotion",
    boys: "55",
    girls: "45",
  },
  {
    class: 9,
    group: "science",
    section: "B",
    category: "total",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "B",
    category: "muslim",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "B",
    category: "hindu",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "B",
    category: "stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "B",
    category: "merit_stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "B",
    category: "repeater",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "B",
    category: "transfer_in",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "B",
    category: "transfer_out",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "B",
    category: "final_attendence",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "B",
    category: "final_promotion",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "c",
    category: "total",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "c",
    category: "muslim",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "c",
    category: "hindu",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "c",
    category: "stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "c",
    category: "merit_stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "c",
    category: "repeater",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "c",
    category: "transfer_in",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "c",
    category: "transfer_out",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "c",
    category: "final_attendence",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "science",
    section: "c",
    category: "final_promotion",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "A",
    category: "total",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "A",
    category: "muslim",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "A",
    category: "hindu",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "A",
    category: "stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "A",
    category: "merit_stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "A",
    category: "repeater",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "A",
    category: "transfer_in",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "A",
    category: "transfer_out",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "A",
    category: "final_attendence",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "A",
    category: "final_promotion",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "B",
    category: "total",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "B",
    category: "muslim",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "B",
    category: "hindu",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "B",
    category: "stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "B",
    category: "merit_stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "B",
    category: "repeater",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "B",
    category: "transfer_in",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "B",
    category: "transfer_out",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "B",
    category: "final_attendence",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "B",
    category: "final_promotion",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "C",
    category: "total",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "C",
    category: "muslim",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "C",
    category: "hindu",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "C",
    category: "stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "C",
    category: "merit_stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "C",
    category: "repeater",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "C",
    category: "transfer_in",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "C",
    category: "transfer_out",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "C",
    category: "final_attendence",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "commerce",
    section: "C",
    category: "final_promotion",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "A",
    category: "total",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "A",
    category: "muslim",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "A",
    category: "hindu",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "A",
    category: "stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "A",
    category: "merit_stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "A",
    category: "repeater",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "A",
    category: "transfer_in",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "A",
    category: "transfer_out",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "A",
    category: "final_attendence",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "A",
    category: "final_promotion",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "B",
    category: "total",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "B",
    category: "muslim",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "B",
    category: "hindu",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "B",
    category: "stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "B",
    category: "merit_stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "B",
    category: "repeater",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "B",
    category: "transfer_in",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "B",
    category: "transfer_out",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "B",
    category: "final_attendence",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "B",
    category: "final_promotion",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "C",
    category: "total",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "C",
    category: "muslim",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "C",
    category: "hindu",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "C",
    category: "stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "C",
    category: "merit_stipend",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "C",
    category: "repeater",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "C",
    category: "transfer_in",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "C",
    category: "transfer_out",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "C",
    category: "final_attendence",
    boys: "9",
    girls: "9",
  },
  {
    class: 9,
    group: "arts",
    section: "C",
    category: "final_promotion",
    boys: "9",
    girls: "9",
  },
  {
    class: 10,
    group: "science",
    section: "A",
    category: "total",
    boys: "১০০",
    girls: "৫০",
  },
  {
    class: 10,
    group: "science",
    section: "A",
    category: "muslim",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "A",
    category: "hindu",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "A",
    category: "stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "A",
    category: "merit_stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "A",
    category: "repeater",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "A",
    category: "transfer_in",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "A",
    category: "transfer_out",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "A",
    category: "final_attendence",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "A",
    category: "final_promotion",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "B",
    category: "total",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "B",
    category: "muslim",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "B",
    category: "hindu",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "B",
    category: "stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "B",
    category: "merit_stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "B",
    category: "repeater",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "B",
    category: "transfer_in",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "B",
    category: "transfer_out",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "B",
    category: "final_attendence",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "B",
    category: "final_promotion",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "C",
    category: "total",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "C",
    category: "muslim",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "C",
    category: "hindu",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "C",
    category: "stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "C",
    category: "merit_stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "C",
    category: "repeater",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "C",
    category: "transfer_in",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "C",
    category: "transfer_out",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "C",
    category: "final_attendence",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "science",
    section: "C",
    category: "final_promotion",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "A",
    category: "total",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "A",
    category: "muslim",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "A",
    category: "hindu",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "A",
    category: "stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "A",
    category: "merit_stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "A",
    category: "repeater",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "A",
    category: "transfer_in",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "A",
    category: "transfer_out",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "A",
    category: "final_attendence",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "A",
    category: "final_promotion",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "B",
    category: "total",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "B",
    category: "muslim",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "B",
    category: "hindu",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "B",
    category: "stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "B",
    category: "merit_stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "B",
    category: "repeater",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "B",
    category: "transfer_in",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "B",
    category: "transfer_out",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "B",
    category: "final_attendence",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "B",
    category: "final_promotion",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "C",
    category: "total",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "C",
    category: "muslim",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "C",
    category: "hindu",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "C",
    category: "stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "C",
    category: "merit_stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "C",
    category: "repeater",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "C",
    category: "transfer_in",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "C",
    category: "transfer_out",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "C",
    category: "final_attendence",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "commerce",
    section: "C",
    category: "final_promotion",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "A",
    category: "total",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "A",
    category: "muslim",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "A",
    category: "hindu",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "A",
    category: "stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "A",
    category: "merit_stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "A",
    category: "repeater",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "A",
    category: "transfer_in",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "A",
    category: "transfer_out",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "A",
    category: "final_attendence",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "A",
    category: "final_promotion",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "B",
    category: "total",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "B",
    category: "muslim",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "B",
    category: "hindu",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "B",
    category: "stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "B",
    category: "merit_stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "B",
    category: "repeater",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "B",
    category: "transfer_in",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "B",
    category: "transfer_out",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "B",
    category: "final_attendence",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "B",
    category: "final_promotion",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "C",
    category: "total",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "C",
    category: "muslim",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "C",
    category: "hindu",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "C",
    category: "stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "C",
    category: "merit_stipend",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "C",
    category: "repeater",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "C",
    category: "transfer_in",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "C",
    category: "transfer_out",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "C",
    category: "final_attendence",
    boys: "10",
    girls: "10",
  },
  {
    class: 10,
    group: "arts",
    section: "C",
    category: "final_promotion",
    boys: "10",
    girls: "10",
  },
];

const six = {};
const seven = {};
const eight = {};
const nineSc = {};
const nineCom = {};
const nineArts = {};
const tenSc = {};
const tenCom = {};
const tenArts = {};

/*
data.map((e) => {
  if (e.class == 6) {
    if (!six[e.section]) {
      six[e.section] = {};
    }
    if (!six[e.section][e.category]) {
      six[e.section][e.category] = {};
    }
    if (!six[e.section][e.category].boys) {
      six[e.section][e.category].boys = e.boys;
      six[e.section][e.category].girls = e.girls;
    }
  }
});
*/
data.map((e) => {
  if (e.class == 6) {
    generateSectionData(e, six, 6, "");
  } else if (e.class == 7) {
    generateSectionData(e, seven, 7, "");
  } else if (e.class == 8) {
    generateSectionData(e, eight, 8, "");
  } else if (e.class == 9 && e.group == "science") {
    generateSectionData(e, nineSc, 9, "science");
  } else if (e.class == 9 && e.group == "commerce") {
    generateSectionData(e, nineCom, 9, "commerce");
  } else if (e.class == 9 && e.group == "arts") {
    generateSectionData(e, nineArts, 9, "arts");
  } else if (e.class == 10 && e.group == "science") {
    generateSectionData(e, tenSc, 10, "science");
  } else if (e.class == 10 && e.group == "commerce") {
    generateSectionData(e, tenCom, 10, "commerce");
  } else if (e.class == 10 && e.group == "arts") {
    generateSectionData(e, tenArts, 10, "arts");
  }
});

function generateSectionData(data, objName, cls, grp) {
  if (data.class == cls && data.group == grp) {
    if (!objName[data.section]) {
      objName.class = cls;
      objName.group = grp;
      objName[data.section] = {};
    }
    if (!objName[data.section][data.category]) {
      objName[data.section][data.category] = {};
    }
    if (!objName[data.section][data.category].boys) {
      objName[data.section][data.category].boys = data.boys;
      objName[data.section][data.category].girls = data.girls;
    }
  }
}

console.log(JSON.stringify(eight));
